name: Run Unit Tests via PyTest

on:
  workflow_dispatch:

jobs:
  build-and-run-tests:
    name: Configure and run tests
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_REGION_NAME: us-east-1      # added this to satisfy settings.AWS_REGION_NAME
    steps:
      - name: Check out repository to the runner
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then python -m pip install . ; fi
      - name: Lint with Ruff
        run: |
          ruff check .
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
